--- #YAML:1.0
name:               Net-Lujoyglamour
version:            0.0.1
abstract:           Create short URLs with luxury and glamour
author:
    - JJ Merelo <jj@merelo.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI::Application:     0
    CGI::Application::Plugin::DBH:  0
    CGI::Application::Plugin::DBIx::Class:  0
    CGI::Application::Plugin::Redirect:  0
    DBIx::Class::Schema:  0
    Exporter:             0
    JSON:                 0
    Regexp::Common:       0
    String::Random:       0
    Test::More:           0
    Test::WWW::Mechanize::CGIApp:  0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
